### ISSUE TITLE
bug if labels contain braces

### ISSUE THREAD

**Issue by orthoceros** [dlech/gmailbuttons#18]
Hi dlech,

I have tried your add-on and think it is a great idea! :+1: 
  Unfortunately it is not entirely compatible with several of my labels: I use folders and labels like "2) science / A) administration" (without quotes) and whenever a mail has two or more labels like these, the second one (even if it has no brace) gets truncated and is incorrectly displayed. Note that the first label is always correctly displayed (with braces, without quotes and showing the full label path, if its not just a root folder).
  Examples of incorrectly displayed second labels: Most often it just displays a quote and the number of my label, e.g. "2; the rest is truncated. I also have seen things like: "\\Important" "2 (the quotes are displayed). If I create a label folder hierarchy without braces in the label names, it works; therefore I suspect the braces are the culprits...

Can you reproduce this? 
Thanks.

**Comment by dlech** [comment]
Sorry I never responded. I will have a look at this.

**Comment by dlech** [comment]
This has been fixed in v0.7.0b1.

https://addons.mozilla.org/en-US/thunderbird/addon/gmailbuttons/versions/?page=1#version-0.7.0b1
