### ISSUE TITLE
Unknown parameter: X-GM-THRID

### ISSUE THREAD

**Issue by lcolman** [dlech/gmailbuttons#25]
Hi,

Experiencing issue of Thunderbird displaying a message stating that the mailserver responded with "Error in IMAP command UID FETCH: Unknown parameter: X-GM-THRID."
This happens on non-Gmail IMAP accounts (who'se about:config is_gmail flag is set to false).
Not sure if this may be server-specific, the server at issue's serverIDResponse is: ("name" "Dovecot").

Thanks.

**Comment by dlech** [comment]
What version of Thunderbird are you using?

Can you try resetting (via right-click) or deleting the `is_gmail` preference for that mail account. Sometimes having the preference set to the default value still results in different behavior than having the preference not set at all.

**Comment by lcolman** [comment]
Using the latest release version, 38.1.0.

I've reset all the is_gmail preferences, set them individually for each mail account - made sure the affected non-Gmail IMAP has `is_gmail` set to false.  Still getting the same error message.
It's not critical to the mail experience (I can still do everything normally) - it is just that having this error message pop-up every time I open an email on that account is a nuisance.

**Comment by lcolman** [comment]
I've just switched from the release version (0.5.0) to the development channel (0.7.0b1), and now this behaviour seems to have stopped.  Not sure what would have been causing it in the current version, but as long as it's fixed in the beta I suppose it will be alright in the future.
