### ISSUE TITLE
Thunderbird 38.2.0 support

### ISSUE THREAD

**Issue by roy7** [dlech/gmailbuttons#26]
When updating Thunderbird today, it won't let me turn GMail Buttons 0.5.1 off the dev channel back on, saying it's incompatible.

**Comment by roy7** [comment]
A tooltip tells me "Add-on has opted into strict compatibility checking".

**Comment by dlech** [comment]
There are more recent versions on the dev channel.

**Comment by roy7** [comment]
My mistake! Thanks. Dev channel version is working fine.
