### ISSUE TITLE
Does not work with Oauth2 in TB 38

### ISSUE THREAD

**Issue by dlech** [dlech/gmailbuttons#27]
Thunderbird 38 introduced Oauth2 authentication for Gmail accounts.

When selecting a message, you will see an error that says:

> closing socket 2
> 
> 1 NO Empty username or password <random-token>

**Comment by dlech** [comment]
You can work around this for now by not using Oauth2. There are a couple things you need to change. In you google account setting (this is under regular google account settings, not gmail settings), under *Sign-in and Security > Connected Apps & Sites* you need to enable less secure apps.

<img width="593" alt="sent mail 476" src="https://cloud.githubusercontent.com/assets/963645/10340134/4b680a74-6cd4-11e5-8593-1e8928fc4f44.png">

If you have been using Thunderbird for a while, this is probably already on.

Then in your Thunderbird Server Settings for your gmail account, you need to change the Authentication Method from Oauth2 to Normal Password

<img width="711" alt="eaihaeje" src="https://cloud.githubusercontent.com/assets/963645/10340150/64d7422c-6cd4-11e5-8e33-4de05826dca2.png">

Then restart Thunderbird.

**Comment by ChezRD** [comment]
And what if I DO NOT WANT to enable less secure apps?

**Comment by dlech** [comment]
You have some options.

1. Add this feature yourself (and send me a pull request)
2. Hire someone to add this feature (and have him/her seed me a pull request)
3. Wait for someone else to add this feature (and send me a pull request)
4. Wait for me to add this feature (not a high priority for me right now, but I will probably get around to it eventually)
5. Don't use this addon

**Comment by ChezRD** [comment]
Or just update to 38.01 ;D

**Comment by SanderGit** [comment]
@ChezRD Even in Thunderbird 42.0 the workaround from @dlech was necessary. After restarting Thunderbird the issue did not occur anymore.
