### ISSUE TITLE
Not working on Thunderbird 52.2

### ISSUE THREAD

**Issue by jlp78** [dlech/gmailbuttons#31]
I got an update to Thunderbird, and now the gmailbuttons extension won't load because it reports as incompatible.

**Comment by pols12** [comment]
Current stable release does not work but dev version can be installed.

However I don’t see how to work with labels. Label managing is checked in options but I don’t see any interface to view, add or remove labels.

**Comment by dlech** [comment]
Should be working with v0.7.x

https://github.com/dlech/gmailbuttons/releases/tag/v0.7.2
