### ISSUE TITLE
Thunderbird 60 can't open options window

### ISSUE THREAD

**Issue by pejotigrek** [dlech/gmailbuttons#33]
I've just installed [this 0.8.0](https://github.com/dlech/gmailbuttons/tree/v0.8.0) version, and first of all: can't see gmail ~~buttons~~ _labels_ in the header and also when trying to change some settings, I've got a "not found" error:
![image](https://user-images.githubusercontent.com/10796588/44122698-4b7e5b08-a025-11e8-8687-234c94bfc6f7.png)
here's quick translation [my ui-lang is polish]:
```
The file was not found
It was not possible to find the file "chrome: //gmailbuttons/content/gmailbuttonsOptions.xul". Check the path to the file, and then try again.
- Check the capitalization and make sure that the file name does not contain typos or other spelling mistakes.
- Check if the file has been moved, deleted or its name has not been changed.
```

my OS is Win10 if it's important.

EDIT: changed "gmail _buttons_" to "gmail _labels_" - because labels are the part that is missing/

**Comment by dlech** [comment]
I messed up packing v0.8.0. Please try v0.8.1.

https://github.com/dlech/gmailbuttons/releases/tag/v0.8.1

**Comment by pejotigrek** [comment]
thank you!
looks like the options and labels are back! :)
