### ISSUE TITLE
add-on triggers exception: [javascript application] Failed to connect via oauth:...

### ISSUE THREAD

**Issue by PackElend** [dlech/gmailbuttons#34]
Thunderbird 60.0b11 (32-bit)
Gmail Buttons 0.8.1
Win 10 Enterprise 1703

1. Thunderbird beta 11 update leads to the exception 
 `[javascript application] Failed to connect via oauth: _token no._`
3. If I disable Gmail Buttons 0.8.1, the problem is gone.
4. No master password is set.
5. I suspect it is also the reason why oauth is triggered is each time I start TB

I think that is the cause:

```
    TypeError: oauth.buildXOAuth2String is not a function[Learn More] gmailbuttonsOverlay.js:489:26
    onSuccess chrome://gmailbuttons/content/gmailbuttonsOverlay.js:489:26
    connect/onPromptAuthAvailable/< jar:file:///C:/MEINS/TOOLS/Mozilla%20Thunderbird%20Beta/omni.ja!/components/msgOAuth2Module.js:145:11
    onRequestTokenReceived resource:///modules/OAuth2.jsm:230:9
    onRequestTokenReceived self-hosted:978:17
    httpRequest/xhr.onload resource://gre/modules/Http.jsm:70:9
```

**installed Extensions**

Addressbooks Synchronizer 1.2.2 true addressbookssync@ggbs.de
Auto Save Drafts Folders 0.3.0 true asdf@d.lech
Automatic Dictionary 1.10.4 true automatic_dictionary_extension@jordi_beltran.net
Before Tabs Toolbar 1.7 true btt@paenglab.ch
Contact Tabs 2.6.4 true contacttabs@janek.org
External Editor 1.0.3 true {11d1a081-b8c3-4002-af38-6ad3e899fdfa}
Gmail Buttons 0.8.1 true gmailbuttons@d.lech
IMAP Draft Unread 1.1.2 true imapdraftunread@micz.it
Lightning 6.2b6 true {e2fda1a4-762b-4020-b5ad-a41df1933103}
Lightning Invitation Notifier (LIN) 1.4 true lightninginvitationnotifier@markus.pullmann
Manually sort folders 1.1.1 true tbsortfolders@xulforum.org
MRC Compose 1.9.0 true mrc_compose@mr-consultant.net
Provider for Google Calendar 4.4.1 true {a62ef8ec-5fdc-40c2-873c-223b8a6925cc}
Quicktext 1.1 true {8845E3B3-E8FB-40E2-95E9-EC40294818C4}
Signature Switch 1.7.1 true {2ab1b709-ba03-4361-abf9-c50b964ff75d}
Stop Ignoring Reply:To 1.2 true stopignoringreplyto@gelvins.com
TbSync 0.7.15 true tbsync@jobisoft.de
ThunderHTMLedit 1.8.5 true jorgk@thunderHTMLedit
G-Hub Lite 6.0.0 false thundervoice@chris.schiffner
Thunderbird Conversations 2.14.4 false gconversation@xulforum.org

**Comment by LawHoo** [comment]
The same issue is happening in Thunderbird 60.2.1. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1497283

**Comment by dlech** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1176399#c122

https://hg.mozilla.org/comm-central/rev/749cb8eaaea2

This change was backported to TB 52 and 60. There is unfortunately not a trivial fix.

**Comment by dlech** [comment]
Workaround is to not use OAUTH authentication.

**Comment by dlech** [comment]
Please try https://github.com/dlech/gmailbuttons/releases/tag/v0.8.2

**Comment by xnrand** [comment]
@dlech Couldn't this be worked around? Looks like oauth.connect() now takes care of authentication itself - so calling builldXOAuth2String might just no longer be needed for new Thunderbird versions.

**Comment by dlech** [comment]
I don't know. Oauth seems to be totally broken in TB 60.2.1 today. I can't even get it working for my test gmail account with all addons disabled.

**Comment by techphd** [comment]
Any update on getting gmailbuttons to work with current TB 60.x versions using oAuth. Only have oAuth option for G Suite setup by administrator. Been missing the Google Labels for months now with no alternative within Thunderbird.

**Comment by kael** [comment]
@dlech Not sure why the `Oauth2Module.buildXOAuth2String` method has been removed, but it's easily to substitute (from the [source](https://hg.mozilla.org/comm-central/file/eae1195fde6d/mailnews/base/src/msgOAuth2Module.js#l151)):

```js
  buildXOAuth2String() {
    return btoa("user=" + this._username + "\x01auth=Bearer " +
      this._oauth.accessToken + "\x01\x01");
  },
```

Would it be enough for a fix ?

**Comment by sterburg** [comment]
v0.8.2 downloaded from github didn't work for me on TB 60.8.0 (64-bit) at all. I got a "404 not found" on opening the "properties" page and nothing seemed to work (no errors).
Did i install it wrong? "install from file"....

Also if this issue is closed why isn't v0.8.2 in the mozilla store?

**Comment by dlech** [comment]
OAuth should be fixed in v1.0.0 for TB 68

**Comment by techphd** [comment]
Excited to have gmailbuttons back after a long time since I use Oauth. Switched from the 60.8 to the beta 69 but says not supported. Those numbers change so often, can you create a release that will work with 69, 70, etc without needing constant new versions? Thanks David. Again, nice work.

**Comment by dlech** [comment]
I am a bit hesitant about doing that because Thunderbird keeps making breaking changes in every release. e.g. https://developer.thunderbird.net/add-ons/updates/tb76

I'll try to keep up with the ESR releases, but I don't really have time to keep up with the in-between versions that are only used by a handful of people.

**Comment by techphd** [comment]
Thanks David, guess the issue is there are no non-beta versions that work with this add-on. I just went to the Thunderbird site today and beta 69 is what was downloaded. One option is turn-off updates and get beta 68, I'll try that. Says the config for 69 is not backward compatible with 68 and won't let me go back and keep my config, cute.

**Comment by dlech** [comment]
tested working with build4 from https://ftp.mozilla.org/pub/thunderbird/candidates/68.0-candidates/
